export const schedule = [
  {
    id: 1,
    fromcode: 'AMD',
    tocode: 'DXB',
    from: 'Ahemadabad',
    to: 'Dubai',
    depaturetime: '01.20 hrs',
    arrivaltime: '02.55 hrs',
    depaturedata: '26 Jul 22',
    arrivaldate: '26 Jul 22',
    flightnumber: '6E 71(NA230)',
    selected: false,
  },
  {
    id: 2,
    fromcode: 'CHE',
    tocode: 'DEL',
    from: 'Chennai',
    to: 'Delhi',
    depaturetime: '12.20 hrs',
    arrivaltime: '1.30 hrs',
    depaturedate: '27 Jul 22',
    arrivaldate: '27 Jul 22',
    flightnumber: '7B 69(SP425)',
    selected: false,
  },
  {
    id: 3,
    fromcode: 'GOA',
    tocode: 'MUB',
    from: 'GOA',
    to: 'Mumbai',
    depaturetime: '04.30 hrs',
    arrivaltime: '05.10 hrs',
    depaturedata: '29 Jul 22',
    arrivaldate: '30 Jul 22',
    flightnumber: '2D 55(AI651)',
    selected: false,
  },
];
